name: Sounding Workflow

on:
  workflow_dispatch:
    inputs:
      force_refresh:
        description: 'Ignore cache and download fresh data?'
        type: boolean
        default: false
  schedule:
    - cron: '0 6 * * *'

jobs:
  run-plot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Weather Data
        uses: actions/cache@v3
        with:
          path: cache_data
          key: ${{ runner.os }}-weather-v1-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-weather-v1-

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libeccodes-dev
          pip install metpy xarray cfgrib meteodata-lab pandas matplotlib netCDF4

      - name: Fetch Data
        env:
          FORCE_REFRESH: ${{ github.event.inputs.force_refresh }}
        run: python fetch_data.py

      - name: Generate Plot
        run: python plot_skewt.py

      - uses: actions/upload-artifact@v4
        with:
          name: skewt-plot
          path: "*.png"
